# Generated by Django 4.2.7 on 2024-01-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
    ]
