# Generated by Django 5.0.1 on 2024-02-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
